name: Add Recently Created Pull Requests to Project Column
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Automate Repo1
      uses: subhamX/github@v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        COLUMN_NAME: Progress
        PROJECT_URL: https://github.com/orgs/hercules-iitrpr/projects/1/
        REPO_URL: https://github.com/hercules-iitrpr/test-project-automation/
